export {default as Welcome} from './Welcome'
export {default as Dashboard} from './Dashboard'
export {default as Search} from './Search'
export {default as Home} from './Home'
export {default as Statistics} from './Statistics'
export {default as Wallet} from './WalletPage'
export {default as Menu} from './menu'